### ISSUE TITLE
Research – Laws and Regs

### ISSUE THREAD

**Issue by colinmurphy01** [usdoj-crt/beta-ada#18]
### Context
Laws and regs is our next content type to develop a strategy for the new beta site.

### Links
- [ADA Laws and Regs](https://www.ada.gov/2010_regs.htm)

### This issue is done when
- [ ] we understand the primary, secondary and tertiary users
- [ ] we understand the use cases and pain points
- [ ] we understand how it's hosted and managed, and current format/components
- [ ] we have documented our findings and shared with stakeholders (?)
- [ ] TBD
- [ ] we are ready to design a solution for the beta site (a possible template?)
