### ISSUE TITLE
ADA Roadmap + Rollout - Update / Align

### ISSUE THREAD

**Issue by colinmurphy01** [usdoj-crt/beta-ada#32]
### Context
As we're building out the initial templates according to the Acquia scope, as a Product Team we need to align on what we want to focus on for this initial rollout phase and then beyond that, including design, tech and content priorities.

### This job is done when
- [x] The product team is aligned on the rollout phases and focus areas
- [x] The roadmap updates are documented and summarized
- [x] The champions are aligned on the rollout phases and focus areas
- [ ] Roadmap added to Github README / wiki

**Comment by colinmurphy01** [comment]
@kstitch7 will be leading a shareout of the roadmap and rollout phases with ADA Champions + Kathy on Thursday 5-5:30pm EST.

**Comment by colinmurphy01** [comment]
@kstitch7 let's discuss next week, how we might use the Github wiki to host roadmap info. @lauraponce was also thinking of hosting research findings there as well.
